

SLOT_VALS = [
    'attraction area',
    'attraction name',
    'attraction type',
     'hospital department',
     'hotel area',
     'hotel book day',
     'hotel book people',
     'hotel book stay',
     'hotel internet',
     'hotel name',
     'hotel parking',
     'hotel pricerange',
     'hotel stars',
     'hotel type',
     'restaurant area',
     'restaurant book day',
     'restaurant book people',
     'restaurant book time',
     'restaurant food',
     'restaurant name',
     'restaurant pricerange',
     'taxi arriveby',
     'taxi departure',
     'taxi destination',
     'taxi leaveat',
     'train arriveby',
     'train book people',
     'train day',
     'train departure',
     'train destination',
     'train leaveat'
]
